export const states = [
  { value: 'AA', title: 'Armed Forces - Americas' },
  { value: 'AE', title: 'Armed Forces - Europe' },
  { value: 'AK', title: 'Alaska' },
  { value: 'AL', title: 'Alabama' },
  { value: 'AP', title: 'Armed Forces - Pacific' },
  { value: 'AR', title: 'Arkansas' },
  { value: 'AS', title: 'American Samoa' },
  { value: 'AZ', title: 'Arizona' },
  { value: 'CA', title: 'California' },
  { value: 'CO', title: 'Colorado' },
  { value: 'CT', title: 'Connecticut' },
  { value: 'DC', title: 'District of Columbia' },
  { value: 'DE', title: 'Delaware' },
  { value: 'FL', title: 'Florida' },
  { value: 'GA', title: 'Georgia' },
  { value: 'GU', title: 'Guam' },
  { value: 'HI', title: 'Hawaii' },
  { value: 'IA', title: 'Iowa' },
  { value: 'ID', title: 'Idaho' },
  { value: 'IL', title: 'Illinois' },
  { value: 'IN', title: 'Indiana' },
  { value: 'KS', title: 'Kansas' },
  { value: 'KY', title: 'Kentucky' },
  { value: 'LA', title: 'Louisiana' },
  { value: 'MA', title: 'Massachusetts' },
  { value: 'MD', title: 'Maryland' },
  { value: 'ME', title: 'Maine' },
  { value: 'MI', title: 'Michigan' },
  { value: 'MN', title: 'Minnesota' },
  { value: 'MO', title: 'Missouri' },
  { value: 'MP', title: 'Northern Mariana Islands' },
  { value: 'MS', title: 'Mississippi' },
  { value: 'MT', title: 'Montana' },
  { value: 'NC', title: 'North Carolina' },
  { value: 'ND', title: 'North Dakota' },
  { value: 'NE', title: 'Nebraska' },
  { value: 'NH', title: 'New Hampshire' },
  { value: 'NJ', title: 'New Jersey' },
  { value: 'NM', title: 'New Mexico' },
  { value: 'NV', title: 'Nevada' },
  { value: 'NY', title: 'New York' },
  { value: 'OH', title: 'Ohio' },
  { value: 'OK', title: 'Oklahoma' },
  { value: 'OR', title: 'Oregon' },
  { value: 'PA', title: 'Pennsylvania' },
  { value: 'PR', title: 'Puerto Rico' },
  { value: 'PW', title: 'Palau' },
  { value: 'RI', title: 'Rhode Island' },
  { value: 'SC', title: 'South Carolina' },
  { value: 'SD', title: 'South Dakota' },
  { value: 'TN', title: 'Tennessee' },
  { value: 'TX', title: 'Texas' },
  { value: 'UT', title: 'Utah' },
  { value: 'VA', title: 'Virginia' },
  { value: 'VI', title: 'Virgin Islands' },
  { value: 'VT', title: 'Vermont' },
  { value: 'WA', title: 'Washington' },
  { value: 'WI', title: 'Wisconsin' },
  { value: 'WV', title: 'West Virginia' },
  { value: 'WY', title: 'Wyoming' },
];
