// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:468d514c-4a6a-4eac-874a-53e9c345cf00',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'merchantportalfronte-hosting-mobilehub-1154637274',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1ttrg2voz2uem.cloudfront.net',
    'aws_mobile_analytics_app_id': '71d718f1a337476b972f20a787837967',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '347eb1c9-e984-4931-8aed-8b2535db323b',
    'aws_project_name': 'merchant-portal-frontend',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'merchantportalfronte-mobilehub-1154637274',
}

export default awsmobile;
